### ISSUE TITLE
Query Execution Failure

### ISSUE THREAD

**Issue by barrymccallarcadia** [yahoo/ariel#1]
## Description
Spitting trace for query failure:
ERROR: Query Execution Failure (SELECT DISTINCT product_location, product_region FROM athenacurcfn_svc_ariel_tool_report.cur WHERE line_item_usage_start_date >= cast('2019-06-10 00:00:00' as timestamp) AND line_item_usage_start_date < cast('2019-07-08 00:00:00' as timestamp) AND product_operation = 'RunInstances')

## Expected Behavior
Table 'cur' doesn't exist. athena db name is correct; however, it seems to have created a table named after my report name, rather than a table named 'cur' 

## Actual Behavior
Me thinks that the crawler.cfn typically makes a table named 'cur' but because I specified a name, it created a different table. (My table name is 'svc_ariel_tool_report') 

## Possible Fix
parameterize the table name in the config yaml. I can specify the db name; however, I can't override the table name. It appears to be hardcoded in get_locations.py:62

## Steps to Reproduce
Create a billing report with a custom name and prefix.

## Your Environment
VPC roll out with aurora db

**Comment by meckstmd** [comment]
@barrymccallarcadia thank you for making us aware of this.  We are testing this internally to verify this and will get back to you with our findings.

**Comment by barrymccallarcadia** [comment]
@meckstmd please reach out out-of-band if you need additional details.

**Comment by meckstmd** [comment]
@barrymccallarcadia I verified this issue is as you described it.  The table name is created with the same name as the name of the report.  Our report is named "cur" and the code is hardcoded to this in a few places so ariel will not work unless the report is called cur.  I have coded a fix to add a new config option for this and in my initial testing it seems to work well.  I should have a fix out for this soon.  One thing I did notice is you can see exactly what the table structure is that Athena creates by going to the following file in s3: 
 s3://${BUCKET_NAME}/${PREFIX_NAME}/${REPORT_NAME}/20190701-20190801/cur-create-table.sql

**Comment by barrymccallarcadia** [comment]
Super info. Thanks @meckstmd. Will watch for commit. I should be able to just torch my existing cfn for the lambda, re-execute package.sh and roll the lambda again while utilizing the existing underlying already established report, athena, s3 locations etc. If I've missed something let me know. 

I also checked the location you specified. The create table statement in our configuration is 
`CREATE EXTERNAL TABLE svc-ariel-tool-report.svc_ariel_tool_report`

**Comment by meckstmd** [comment]
Your welcome @barrymccallarcadia   I just submitted a PR for a fix that I tested that worked.  I don't want to merge it yet because I want to give people on the team a chance to look at it.  You should be able to try it out by cloning from https://github.com/meckstmd/ariel/tree/fix-issue-001.  Make sure you use the `fix-issue-001` branch and not the master.   The process you described above should work fine for testing it out.  You will need to set the `CUR_TABLE_NAME` configuration option to `svc_ariel_tool_report`.  Also, you will need at least 14 days of data to complete a run or you will get an Insufficient data error since that is how much data it needs to give good estimates of how many RIs you will need.  Let me know how it works you

**Comment by meckstmd** [comment]
@barrymccallarcadia I just merged the PR so this issue is fixed.  I'm still working on https://github.com/yahoo/ariel/issues/3
