### ISSUE TITLE
'instancetype': KeyError

### ISSUE THREAD

**Issue by opennomad** [yahoo/ariel#8]
New set up produces an error after running for a while. We don't currently have an RIs in use and I looks like this might be due to that.

## Description
The Lambda fails with an error in account without RIs currently in use.

## Expected Behavior
Report should run to completion without error

## Actual Behavior
Report fails with the following error:

```
'instancetype': KeyError
Traceback (most recent call last):
File "/var/task/ariel/lambda.py", line 106, in handler
lambda_main(utils.load_config(config))
File "/var/task/ariel/lambda.py", line 42, in lambda_main
reports = generate_reports.generate(config, instances, ris, pricing)
File "/var/task/ariel/generate_reports.py", line 64, in generate
family_column = ris.columns.get_loc('instancetype') + 1
File "/var/task/pandas/core/indexes/base.py", line 2892, in get_loc
return self._engine.get_loc(self._maybe_cast_indexer(key))
File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'instancetype'
```

## Possible Fix

Initialize the `ris` variable data that is passed into `generate()`.

## Steps to Reproduce
Attempt to run report in account without RIs

## Context
Just trying to run the report.

## Your Environment
* Version used: 2.0.3

**Comment by meckstmd** [comment]
@opennomad thanks for using Ariel and finding and logging this issue.  I created a fix for this with PR #9.  Check it out and let me know if it works for you.

**Comment by opennomad** [comment]
Thanks @meckstmd for the fix, sadly it still failed with a different error. Here is the result returned by the function:

```
{
  "errorMessage": "'instancetype'",
  "errorType": "KeyError",
  "stackTrace": [
    [
      "/var/task/ariel/lambda.py",
      106,
      "handler",
      "lambda_main(utils.load_config(config))"
    ],
    [
      "/var/task/ariel/lambda.py",
      42,
      "lambda_main",
      "reports = generate_reports.generate(config, instances, ris, pricing)"
    ],
    [
      "/var/task/ariel/generate_reports.py",
      64,
      "generate",
      "family_column = ris.columns.get_loc('instancetype') + 1"
    ],
    [
      "/var/task/pandas/core/indexes/base.py",
      2892,
      "get_loc",
      "return self._engine.get_loc(self._maybe_cast_indexer(key))"
    ],
    [
      "pandas/_libs/index.pyx",
      107,
      "pandas._libs.index.IndexEngine.get_loc",
      ""
    ],
    [
      "pandas/_libs/index.pyx",
      131,
      "pandas._libs.index.IndexEngine.get_loc",
      ""
    ],
    [
      "pandas/_libs/hashtable_class_helper.pxi",
      1607,
      "pandas._libs.hashtable.PyObjectHashTable.get_item",
      ""
    ],
    [
      "pandas/_libs/hashtable_class_helper.pxi",
      1614,
      "pandas._libs.hashtable.PyObjectHashTable.get_item",
      ""
    ]
  ]
}
```

And here is the log output:

```
START RequestId: 0c357188-722e-4155-9125-bda8df96b5ef Version: $LATEST
'instancetype': KeyError
Traceback (most recent call last):
  File "/var/task/ariel/lambda.py", line 106, in handler
    lambda_main(utils.load_config(config))
  File "/var/task/ariel/lambda.py", line 42, in lambda_main
    reports = generate_reports.generate(config, instances, ris, pricing)
  File "/var/task/ariel/generate_reports.py", line 64, in generate
    family_column = ris.columns.get_loc('instancetype') + 1
  File "/var/task/pandas/core/indexes/base.py", line 2892, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'instancetype'
```

we'll likely move forward and just purchase a couple of RIs since we know we need them.

**Comment by meckstmd** [comment]
@opennomad that's the exact same error as before.  Are you sure you pulled the code for the PR from the correct place?   I have not merged it yet. You need to pull it from https://github.com/meckstmd/ariel/tree/fix-issue-008 (my org and the `fix-issue-008` branch). I just ran it and simulated accounts with no RIs and it worked fine.

**Comment by opennomad** [comment]
@meckstmd  Yeah, I pulled down the forked repo and switched to the `fix-issue-008` branch before running the install. I assume I don't have to redo the entire install and just starting at step 4 (install ariel) in the `INSTALL.md` is sufficient?

**Comment by meckstmd** [comment]
@opennomad yeah, step 4 is all you need to do, but did you do both parts of step 4?  The first part is you run `package.sh` to build ariel, zip it up and upload it to S3.  The second part is you need to update the Cloudformation stack.  The directions say create the stack, but since yours already exists, you will need to update the current stack and you update it from the URL which `package.sh` prints out.  Here is an example of the last few lines of the `package.sh` run in which [BUCKET_NAME] would be the S3 bucket name you passed into the script:

```
upload: ./ariel-vpc-2.0.5.yaml to s3://[BUCKET_NAME]/lambda/ariel/2.0.5/ariel-vpc-2.0.5.yaml
Ariel can be installed from : https://s3.amazonaws.com/[BUCKET_NAME]/lambda/ariel/2.0.5/ariel-2.0.5.yaml
                         or : https://s3.amazonaws.com/[BUCKET_NAME]/lambda/ariel/2.0.5/ariel-vpc-2.0.5.yaml
```

So you would update the stack by copying one of the URLs above (depending on whether you are using the VPC one or not) and pasting it into the update cloudformation stack screen as shown in the image below.  Once the stack update is complete, then you can run ariel. 

![image](https://user-images.githubusercontent.com/9009378/63541772-d36d6a80-c4ec-11e9-8f27-21a914a219a4.png)

**Comment by opennomad** [comment]
@meckstmd  Yeah, I pulled down the forked repo and switched to the `fix-issue-008` branch before running the install. I assume I don't have to redo the entire install and just starting at step 4 (install ariel) in the `INSTALL.md` is sufficient?

**Comment by opennomad** [comment]
@meckstmd , yes, I did both steps. I suspect that perhaps the data it was getting may have been stale? This morning I do see a different error, but we also bought a few RIs so it's no longer an empty account. 

Here's the new error, but I think I'll try the original version again now that we have some RIs

```
START RequestId: b12edd5a-a0ef-4f01-8c5c-2805f738cdc3 Version: $LATEST
arrays must all be same length: ValueError
Traceback (most recent call last):
  File "/var/task/ariel/lambda.py", line 106, in handler
    lambda_main(utils.load_config(config))
  File "/var/task/ariel/lambda.py", line 42, in lambda_main
    reports = generate_reports.generate(config, instances, ris, pricing)
  File "/var/task/ariel/generate_reports.py", line 291, in generate
    'coverage_chance': coverage_chance.values,
  File "/var/task/pandas/core/frame.py", line 410, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/var/task/pandas/core/internals/construction.py", line 257, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/var/task/pandas/core/internals/construction.py", line 77, in arrays_to_mgr
    index = extract_index(arrays)
  File "/var/task/pandas/core/internals/construction.py", line 368, in extract_index
    raise ValueError("arrays must all be same length")
ValueError: arrays must all be same length

END RequestId: b12edd5a-a0ef-4f01-8c5c-2805f738cdc3
REPORT RequestId: b12edd5a-a0ef-4f01-8c5c-2805f738cdc3	Duration: 101966.51 ms	Billed Duration: 102000 ms 	Memory Size: 512 MB	Max Memory Used: 186 MB	
```

**Comment by meckstmd** [comment]
@opennomad I am sorry that didn't work for you.  I did merge the PR into prod because it should not break anything and has better initialization.  I think the new error you are getting is because it does not have RI data for the entire period you are analyzing (28 days by default).  I made a commit here: https://github.com/meckstmd/ariel/tree/issue-008-logging which adds some logging.  I didn't PR it because I don't plan to merge it, but am just using it to get some debug info.  If you run it and observe the printout right before you get the error it should look something like this:

`ri_units: 128.0, arraySizes: total_usage=168, floating_ri_units=168, floating_instance_values=168, unused_ri_units=168, coverage_chance=168`

Can you send that along?  I am thinking this error will go away after you have the RIs for long enough.  Perhaps there is some initializing we could do to get you past this, but you do really need a decent amount of data for Ariel to give you good recommendations on what to purchase.

**Comment by opennomad** [comment]
Hi @meckstmd , here is the new error:

```
{
  "errorMessage": "Query Execution Failure",
  "errorType": "RuntimeError",
  "stackTrace": [
    [
      "/var/task/ariel/lambda.py",
      106,
      "handler",
      "lambda_main(utils.load_config(config))"
    ],
    [
      "/var/task/ariel/lambda.py",
      50,
      "lambda_main",
      "reports['UNLIMITED'] = get_unlimited_summary.load(config)"
    ],
    [
      "/var/task/ariel/get_unlimited_summary.py",
      84,
      "load",
      "query_id = utils.execute_athena_query(athena, staging, query)"
    ],
    [
      "/var/task/ariel/utils.py",
      53,
      "execute_athena_query",
      "raise RuntimeError(\"Query Execution Failure\")"
    ]
  ]
}
```

and 

```
START RequestId: a1d4dfc1-7b66-4fb6-8825-fb7066de610c Version: $LATEST
ERROR: Query Execution Failure (SELECT line_item_usage_account_id AS accountid , product_region AS region, lower(product_instance) AS instancetypefamily, sum(line_item_usage_amount) AS unlimitedusageamount, sum(line_item_unblended_cost) AS unlimitedusagecost FROM athenacurcfn_billing_report_for_ariel.Billing_Report_for_Ariel WHERE line_item_usage_type like '%CPUCredits:%' AND line_item_usage_start_date >= cast('2019-08-07 00:00:00' as timestamp) AND line_item_usage_start_date < cast('2019-09-04 00:00:00' as timestamp) AND product_region <> '' AND product_instance <> '' GROUP BY line_item_usage_account_id, product_region, lower(product_instance) ORDER BY line_item_usage_account_id, product_region, lower(product_instance))
{'QueryExecution': {'QueryExecutionId': '43505bfe-a319-441b-a18a-912c294ee7a6', 'Query': "SELECT line_item_usage_account_id AS accountid , product_region AS region, lower(product_instance) AS instancetypefamily, sum(line_item_usage_amount) AS unlimitedusageamount, sum(line_item_unblended_cost) AS unlimitedusagecost FROM athenacurcfn_billing_report_for_ariel.Billing_Report_for_Ariel WHERE line_item_usage_type like '%CPUCredits:%' AND line_item_usage_start_date >= cast('2019-08-07 00:00:00' as timestamp) AND line_item_usage_start_date < cast('2019-09-04 00:00:00' as timestamp) AND product_region <> '' AND product_instance <> '' GROUP BY line_item_usage_account_id, product_region, lower(product_instance) ORDER BY line_item_usage_account_id, product_region, lower(product_instance)", 'ResultConfiguration': {'OutputLocation': 's3://aws-athena-query-results-597764168253-us-east-1/ariel-cur-output/43505bfe-a319-441b-a18a-912c294ee7a6.csv', 'EncryptionConfiguration': {'EncryptionOption': 'SSE_S3'}}, 'QueryExecutionContext': {}, 'Status': {'State': 'FAILED', 'StateChangeReason': "SYNTAX_ERROR: line 1:522: Column 'product_instance' cannot be resolved", 'SubmissionDateTime': datetime.datetime(2019, 9, 5, 18, 40, 39, 675000, tzinfo=tzlocal()), 'CompletionDateTime': datetime.datetime(2019, 9, 5, 18, 40, 40, 3000, tzinfo=tzlocal())}, 'Statistics': {'EngineExecutionTimeInMillis': 202, 'DataScannedInBytes': 0}}, 'ResponseMetadata': {'RequestId': '8755b7d9-a08a-4e87-84b6-573315130f30', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1', 'date': 'Thu, 05 Sep 2019 18:40:39 GMT', 'x-amzn-requestid': '8755b7d9-a08a-4e87-84b6-573315130f30', 'content-length': '2841', 'connection': 'keep-alive'}, 'RetryAttempts': 0}}
Query Execution Failure: RuntimeError
Traceback (most recent call last):
  File "/var/task/ariel/lambda.py", line 106, in handler
    lambda_main(utils.load_config(config))
  File "/var/task/ariel/lambda.py", line 50, in lambda_main
    reports['UNLIMITED'] = get_unlimited_summary.load(config)
  File "/var/task/ariel/get_unlimited_summary.py", line 84, in load
    query_id = utils.execute_athena_query(athena, staging, query)
  File "/var/task/ariel/utils.py", line 53, in execute_athena_query
    raise RuntimeError("Query Execution Failure")
RuntimeError: Query Execution Failure

END RequestId: a1d4dfc1-7b66-4fb6-8825-fb7066de610c
REPORT RequestId: a1d4dfc1-7b66-4fb6-8825-fb7066de610c	Duration: 116735.70 ms	Billed Duration: 116800 ms	Memory Size: 512 MB	Max Memory Used: 191 MB	Init Duration: 1036.06 ms	
XRAY TraceId: 1-5d715623-83118b607ccf3c38924cd217	SegmentId: 3a0a400e7418a864	Sampled: false	
```

It looks like a syntax error.

**Comment by meckstmd** [comment]
@opennomad Try unconfiguring the Unlimited Usage report by removing or commenting out the line in the config for `CSV_REPORTS --> UNLIMITED` (https://github.com/yahoo/ariel/blob/master/config-example.yaml#L41).  The error you are getting is because your CUR report does not have a `product_instance` column in it.  I cannot duplicate this because our CUR report does have that column in it.  My theory is that maybe AWS does not include that in the CUR report if you do not have T* instances in your accounts or they are not configured for unlimited.  In our CUR report, there are three different values for that column (`T3A`, `T3` and `T2`).  Do any of your accounts have T in them and if you do are they configured to allow unlimited usage?  If you do not have T* instance types in your account with unlimited turned on then there is no point in running the unlimited usage report anyway.

If you want to debug this more, can you send me the schema for your cur report.  To export this easily you can go to Athena and run the following query:
`describe athenacurcfn_billing_report_for_ariel.Billing_Report_for_Ariel`

**Comment by meckstmd** [comment]
@opennomad if you want to debug it more, can you send me the schema for your cur report?

**Comment by meckstmd** [comment]
Closing since @opennomad  has not responded in 7 months.
